### ISSUE TITLE
kafica

### ISSUE THREAD

**Issue by debagiranje** [debagiranje/trejding_bot#1]
Potrebno je da odemo na kaficu, kako bismo detaljnije razradili ideju naseg projekta i stavili stogod na papir.
Izaberi gdje i kad @armain0 
Ne bi bilo loshe sutra/prekosutra do 12?
p.s. ovo je samo da vidim kako ovo funkcionise 😄

**Comment by armain0** [comment]
danas bi bilo dobro, ne znam stignemo li?

**Comment by debagiranje** [comment]
Slobodna sam oko 3, do jedno 4.
Može i sutra ujutro prije SI? Tipa oko 11?
Ja danas krećem da ozbiljnije gledam "svoj" dio projekta

**Comment by armain0** [comment]
kontam da je bolje dns ako budemo trebali jos nesto doraditi, moze oko pola 3 tipa? 
mogu bilo gdje, ne znam gdje je tebi lakse, moze ovde sestica ili ab gdje smo i prosli put ili bilo gdje

**Comment by debagiranje** [comment]
AB works really well for me, pola 3 it is. Zatvaram issue.
